site_name: Little-UNIkeEN-Bot
copyright: Copyright 2022 Little-UNIkeEN-Bot by UNIkeEN. All Rights Reserved
repo_name: UNIkeEN/Little-UNIkeEN-Bot
repo_url: https://github.com/UNIkeEN/Little-UNIkeEN-Bot
nav:
    - 主页: 
      - 'index.md'
      - '关于本项目': 'about.md'
      - '更新计划': 'update-plan.md'
      - '授权许可': 'license.md'
    - 开始:
      - '安装': 'get-start/installation.md'
      - '配置驱动器': 'get-start/set-driver.md'
      - '配置 SQL': 'get-start/set-sql.md'
      - '部署 Bot': 'get-start/deployment.md'
      - '遇到问题': 'get-start/question.md'
    - 插件:
      - '插件入门': 'plugin/introduction.md'
      - '插件与数据库': 'plugin/pluginWithSql.md'
      - '定时任务': 'plugin/pluginWithTimer.md'
      - 基本插件:
        - '插件组管理': 'plugin/plugins/groupManagerPlugin.md'
        - '群权限获取': 'plugin/plugins/getPermissionPlugin.md'
        - '帮助插件':   'plugin/plugins/helpPlugin.md'
        - '群消息记录': 'plugin/plugins/messageRecorderPlugin.md'
      - 功能插件:
        - '超级表情':   'plugin/plugins/superEmojiPlugin.md'
        - '早安晚安':   'plugin/plugins/greetingsPlugin.md'
        - '寄了检测':   'plugin/plugins/jilePlugin.md'
        - '新闻':      'plugin/plugins/newsPlugin.md'
        - '二次元图':   'plugin/plugins/2cyPicPlugin.md'
        - '签到':      'plugin/plugins/signinPlugin.md'
        - '答案之书':   'plugin/plugins/chatWithAnswerBookPlugin.md'
        - '问答库':    'plugin/plugins/faqPlugin.md'
        - '轮盘赌':    'plugin/plugins/roulettePlugin.md'
        - '买彩票':    'plugin/plugins/lotteryPlugin.md'
        - '五子棋':    'plugin/plugins/gobangPlugin.md'
        - '模拟炒股':  'plugin/plugins/stocksPlugin.md'
        - 'SJTU教务':  'plugin/plugins/sjtuJwcPlugin.md'
        - 'SJTU新闻':  'plugin/plugins/sjtuNewsPlugin.md'
        - 'SJTU第二课堂': 'plugin/plugins/sjtuDektPlugin.md'
        - 'SJTU canvas日历': 'plugin/plugins/canvasIcsPlugin.md'
    - API:
      - '驱动器对接': 'api/send.md'
      - '运行时警告': 'api/warning.md'
      - '鉴权与插件配置': 'api/auth-config.md'
      - '响应卡片绘制': 'api/draw-card.md'
      - '金币系统': 'api/account-operation.md'
edit_uri: ""
theme:
  name: 'material'
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - toc.integrate
    - navigation.indexes
    - navigation.top
    - search.suggest

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UNIkeEN/Little-UNIkeEN-Bot
  generator: false

plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'

markdown_extensions: 
  - meta
  - admonition # 彩色提示块
  - pymdownx.details # 提示块可以折叠
  - pymdownx.highlight: # 代码高亮
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg





