site_name: Little-UNIkeEN-Bot
copyright: Copyright 2022 Little-UNIkeEN-Bot by UNIkeEN. All Rights Reserved
repo_name: UNIkeEN/Little-UNIkeEN-Bot
repo_url: https://github.com/UNIkeEN/Little-UNIkeEN-Bot
nav:
    - 主页: 
      - 'index.md'
      - '关于本项目': 'about.md'
      - '更新日志': 'update-plan.md'
      - '授权许可': 'license.md'
      - '技术先进性': 'progressiveness.md'
    - 开始:
      - '安装向导': 'get-start/installation.md'
      - '配置 python': 'get-start/set-python.md'
      - '配置 gocqhttp': 'get-start/set-driver.md'
      - '配置 SQL': 'get-start/set-sql.md'
      - '部署 Bot': 'get-start/deployment.md'
      - 'muaLTS分支': 'get-start/muaLTS.md'
      - '遇到问题': 'get-start/question.md'
    - 插件:
      - '插件入门': 'plugin/introduction.md'
      - '插件与数据库': 'plugin/pluginWithSql.md'
      - '定时任务': 'plugin/pluginWithTimer.md'
      - 基础插件:
        - '插件组管理': 'plugin/plugins/groupManagerPlugin.md'
        - '群权限获取': 'plugin/plugins/getPermissionPlugin.md'
        - '帮助插件':   'plugin/plugins/helpPlugin.md'
        - '群消息记录': 'plugin/plugins/messageRecorderPlugin.md'
        - '群文件记录': 'plugin/plugins/fileRecorderPlugin.md'
        - 'gocq离线警告': 'plugin/plugins/gocqWatchDogPlugin.md'
        - '群内自动回拍': 'plugin/plugins/autoRepokePlugin.md'
      - 基本功能插件:
        - '超级表情':   'plugin/plugins/superEmojiPlugin.md'
        - '早安晚安':   'plugin/plugins/greetingsPlugin.md'
        - '寄了检测':   'plugin/plugins/jilePlugin.md'
        - '新闻':      'plugin/plugins/newsPlugin.md'
        - '二次元图':   'plugin/plugins/2cyPicPlugin.md'
        - '签到':      'plugin/plugins/signinPlugin.md'
        - '答案之书':   'plugin/plugins/chatWithAnswerBookPlugin.md'
        - '问答库':    'plugin/plugins/faqPlugin.md'
        - '轮盘赌':    'plugin/plugins/roulettePlugin.md'
        - '买彩票':    'plugin/plugins/lotteryPlugin.md'
        - '五子棋':    'plugin/plugins/gobangPlugin.md'
        - '模拟炒股':  'plugin/plugins/stocksPlugin.md'
        - 'SJMC 服务器状态': 'plugin/plugins/sjmcPlugin.md'
        - 'SJMC 直播间状态': 'plugin/plugins/sjmcLivePlugin.md'
        - 'SJTU 教务':  'plugin/plugins/sjtuJwcPlugin.md'
        - 'SJTU 新闻':  'plugin/plugins/sjtuNewsPlugin.md'
        - 'SJTU 第二课堂': 'plugin/plugins/sjtuDektPlugin.md'
        - 'SJTU canvas日历': 'plugin/plugins/canvasIcsPlugin.md'
        - 'SJTU 核酸点位': 'plugin/plugins/sjtuHesuanPlugin.md'
        - 'SJTU 教室查询': 'plugin/plugins/sjtuClassroomPlugin.md'
        - 'SJTU 麦当劳': 'plugin/plugins/sjtuMddPlugin.md'
        - 'SJTU 校门': 'plugin/plugins/sjtuSchoolGatePlugin.md'
        - '我爱电路实验':  'plugin/plugins/izfPlugin.md'
        - '水群报告': 'plugin/plugins/myactPlugin.md'
        - '昨日词云': 'plugin/plugins/wordcloudPlugin.md'
        - '随机数': 'plugin/plugins/randomNumPlugin.md'
        - 'B站订阅': 'plugin/plugins/bilibiliSubscribePlugin.md'
        - '热搜': 'plugin/plugins/hotSearchPlugin.md'
        - '点歌': 'plugin/plugins/songPlugin.md'
      - MC高校联盟插件:
        - 'MUA通知编辑': 'plugin/plugins/mua/annContextManagerPlugin.md'
        - 'MUA用户token绑定': 'plugin/plugins/mua/muaTokenBindPlugin.md'
        - 'MUA群组token绑定': 'plugin/plugins/mua/muaTargetsPlugin.md'
    - API:
      - '驱动器对接': 'api/send.md'
      - '运行时警告': 'api/warning.md'
      - '鉴权与插件配置': 'api/auth-config.md'
      - '响应卡片绘制': 'api/draw-card.md'
      - '金币系统': 'api/account-operation.md'
      - 'bot管理': 'api/botAdminApi.md'
      - '缓冲队列': 'api/bufferQueue.md'
edit_uri: ""
theme:
  name: 'material'
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - toc.integrate
    - navigation.indexes
    - navigation.top
    - search.suggest

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UNIkeEN/Little-UNIkeEN-Bot
  generator: false

plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'

markdown_extensions: 
  - meta
  - admonition # 彩色提示块
  - pymdownx.details # 提示块可以折叠
  - pymdownx.highlight: # 代码高亮
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js



